* リチャード・ストールマン氏を支援する公開書簡
  :PROPERTIES:
  :CUSTOM_ID: リチャードストールマン氏を支援する公開書簡
  :END:

署名する場合は、*[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][ここ]]をクリックし*、ファイル名を
=<ユーザ名>.yaml= (=<ユーザ名>=を自分の名前に置き換える)
にした上で、以下の内容も入力して下さい:

#+BEGIN_EXAMPLE
  name: <自分の名前> (任意で組織名、または会社名)
  link: <プロフィール、またはサイトへのリンク>
#+END_EXAMPLE

=<>= は除きます。

入力例:

#+BEGIN_EXAMPLE
  name: 山田太郎 (良い会社)
  link: https://github.com/yamada_tarou
#+END_EXAMPLE

このファイルに =<>=
は記述しないようにしてください。また、ファイル名には非 ASCII
文字は入力しないようにしてください。\\
リンク先としてメールアドレスを使う場合は、先頭に =mailto:=
を追加してください。\\
可能であれば、ぜひ実名を使い、丸括弧内にプロジェクトや関係のある団体名を追加してください。

その後、*"Propose new file" をクリックし*、次に表示されるページで Merge
Request を作成してください。

毅然とした態度で。それでも、プロとしての自覚は持ちましょう。

可能であれば、この運動をフォーラムや SNS
に共有し、私達の助けになってくれそうな記者にも伝えることも検討してください。

他の方法として、リポジトリをクローン、フォークした上で、=_data/signed/<ユーザ名>.yaml=
というファイルを手動で作成し、コミットして、PR を出すこともできます。

*Github を使わず*に署名したい場合、このサイトに来てください:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1、\\
もしくは署名されたパッチを
[[mailto:signrms@prog.cf][signrms@prog.cf]]、または
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]]
まで送ってください。

もし、視覚的な助けが必要な場合は、[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][動画]]
(ただし、英語) があります。

*すべての署名は最大で最大 12 時間以内にマージされます - 膨大な量の PR
のため*

** チャットルーム
   :PROPERTIES:
   :CUSTOM_ID: チャットルーム
   :END:

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms

** 連絡先
   :PROPERTIES:
   :CUSTOM_ID: 連絡先
   :END:

出版関係者、YouTuber、またはその他の報道機関の代表者の方であれば、下記のメールでお問い合わせいただけます。

- rms-support-letter@protonmail.com
