* Avoin kirje Richard Stallmanin tueksi
  :PROPERTIES:
  :CUSTOM_ID: avoin-kirje-richard-stallmanin-tueksi
  :END:

Allekirjoittaakseen avoimen kirjeen, paina
*[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][tätä]]*
painiketta ja nimeä tiedosto =<username>.yaml=(korvaa =<username>=
käyttäjänimelläsi). Lisää seuraavat tiedot tiedostoon:

#+BEGIN_EXAMPLE
  name: <Nimesi tähän (yritys tai organisaatio (valinnainen))>
  link: <Linkki profiiliisi tai kotisivullesi>
#+END_EXAMPLE

ilman =<>=-merkkejä.

Esimerkki:

#+BEGIN_EXAMPLE
  name: Maija Meikäläinen (Esimerkki OY)
  link: https://github.com/esimerkki
#+END_EXAMPLE

Älä käytä tiedostossa =<>=-merkkejä tai ei-ASCII-merkkejä (esimerkkinä
emojit) tiedostonimessä. Jos haluat lisätä sähköpostiosoitteesi linkkinä
allekirjoitukseesi, aseta sähköpostiosoitteesi eteen =mailto:=, jotta
sähköpostiosoite tunnistettaisiin linkkinä. Mikäli mahdollista, käytä
allekirjoituksessasi oikeaa nimeäsi ja lisää projektejasi ja edustamiasi
organisaatioita sulkumerkkien sisään.

Kun olet saanut laitettua tiedot allekirjoitustiedostoon, paina
*/Propose new file/*-painiketta ja käy läpi painikkeen painamisen
jälkeen avautuneet sivut lähettääksesi allekirjoituksen pull requestina.

Pidä allekirjoituksesi sisältö ytimekkäänä mutta ammattimaisena.

Mikäli mahdollista, harkitse tämän kirjeen jakamista foorumeilla ja
sosiaalisessa mediassa sekä vinkkaa tämä kirje toimittajille, jotka
voivat mahdollisesti auttaa tämän kirjeen tavoitteita.

Vaihtoehtoisesti, voit kopioida tämän repon, luoda tiedoston
=_data/signed/<username>.yaml= manuaalisesti ja luoda commitin sekä
luoda pull requestin tähän repoon.

Jos haluat tukea kirjettä */Ilman Githubia/*, vieraile tällä sivulla:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1 tai
lähetä allekirjoitettu pätchi sähköpostiosoitteeseen
[[mailto:signrms@prog.cf][signrms@prog.cf]] tai
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

Jos tarvitset tukea allekirjoittamiseen videon avulla, katso ohjevideo
osoitteessa https://invidious.snopyta.org/watch?v=1lz5S5oS8CU (Video
englanniksi).

*/Kaikki allekirjoitukset käydään läpi ja lisätään sivulle 12 tunnin
sisällä allekirjoitusten suuren määrän takia./*

** Keskusteluhuoneet
   :PROPERTIES:
   :CUSTOM_ID: keskusteluhuoneet
   :END:

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms

** Lisensointi
   :PROPERTIES:
   :CUSTOM_ID: lisensointi
   :END:

Kaikki lähdekoodi kirjeen taustalla on yksinomaan GPL-3.0.-lisenssin
alaisuudessa

Kuvat =assets=-kansiossa ovat
[[https://creativecommons.org/licenses/by-sa/3.0/legalcode][CC BY-SA
3.0]]-lisenssin alaisuudessa. Esikatselukuvat perustuvat kuvaan
osoitteessa
https://commons.wikimedia.org/wiki/File:Richard_Matthew_Stallman.jpeg,
joka on julkaistu CC BY-SA 3.0-lisensillä. Esikatselukuva perustuu
kuvaan, jota käytettiin O'Reilly Median julkaiseman
=Free as in Freedom: Richard Stallman's Crusade for Free Software by Sam Williams=-kirjan
kantena, joka on alun perin julkaistu 1. maaliskuuta vuonna 2002
GFDL-lisensillä

Allekirjoituksia ei voi suojata tekijänoikeuksilla.
