* Uma carta aberta de apoio a RMS.
  :PROPERTIES:
  :CUSTOM_ID: uma-carta-aberta-de-apoio-a-rms.
  :END:

Para assinar, *clique
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][aqui]]*
e escreva o nome do ficheiro como =<nomeutilizador>.yaml= (substitua
=<nomeutilizador>= pelo seu nome) com o seguinte conteúdo:

#+BEGIN_EXAMPLE
  name: <o seu nome aqui (opcionalmente o nome da organização ou empresa)>
  link: <o link para o seu perfil pessoal ou website>
#+END_EXAMPLE

Sem os =<>=.

Exemplo:

#+BEGIN_EXAMPLE
  name: Nome Exemplo (Boa empresa)
  link: https://github.com/nome_exemplo
#+END_EXAMPLE

Não use =<>= neste ficheiro, tais como quaisquer simbolos não-ascii no
nome de ficheiro. Se está a usar um email como link coloque o prefixo
=mailto:=. Se lhe for possível, use o seu nome verdadeiro e o nome da
organização ou empresa a que está afiliado entre parenteses.

Depois *clique em "Propor novo ficheiro"* e siga as páginas para criar
um pedido de merge.

Vamos manter um tom firma, mas profissional.

Se puder, considere partilhar esta carta em foruns, redes sociais assim
como notificar os jornalistas que possam ser favoráveis á nossa causa.

*Os pedidos serão aceites dentro de 12 horas - devido a um elevado
volume de PRs PRs eles serão unidos em lote*

Alternativamente, pode fazer fork ou clonar o repositório, criar o
ficheiro =_data/signed/<nomeutilizador>.yaml= manualmente, e de seguida
fazer o commit e submeter o PR.

Se quiser suportar a carta sem usar o GitHub, pode fazê-lo aqui:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, ou
enviar um patch assinado para
[[mailto:signrms@prog.cf][signrms@prog.cf]] or
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

** Salas de chat
   :PROPERTIES:
   :CUSTOM_ID: salas-de-chat
   :END:

- *Matrix.org:* #free-rms:matrix.org
- *IRC:* #free-rms at chat.freenode.net
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
