* Një letër në mbështetje të RMS.
  :PROPERTIES:
  :CUSTOM_ID: një-letër-në-mbështetje-të-rms.
  :END:

Për të firmosur, *kliko
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][këtu]]*
dhe emërtoje filen =<përdorues>.yaml= (zëvëndëso =<përdorues>= me emrin
tënd) me përmbajtjen si më poshtë:

#+BEGIN_EXAMPLE
  name: <emri yt këtu (mund të shkruash kompaninë ose organizatën)>
  link: <link i profilit ose website>
#+END_EXAMPLE

Mos harro shkruhet pa =<>=.

Shembull:

#+BEGIN_EXAMPLE
  name: Emër shembull (Kompania)
  link: https://github.com/user_shembull
#+END_EXAMPLE

Mos përdor =<>= në këtë file, gjithashtu nuk lejohen karakteret jo-ASCII
në emërtimin e filet. Nëse përdor këtë email si link, shtoji =mailto:=.
Nëse ke mundësi, të lutem përdor emrin tënd të vërtetë dhe shto
projektet dhe kompanitë e lidhura në thonjëza teke.

Pastaj *kliko "Propose new file"* dhe ndiq instruksionet për merge
request.

Mbaj një ton të vendosur por profesional.

Nëse keni mundësi, konsideroni shpërndarjen e kësaj letre në forumet
tuaja dhe rrjete sociale dhe informoni gazetarët e kësaj fushe.

Gjithashtu, bëjini fork dhe clone repozitorin, krijoni manualisht file
=_data\signed\<username>.yaml=, commit dhe kërkoni PR.

Nesë doni të suportoni letrën jashtë Github, shkoni tek:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, ose
dërgoni një patch të firmosur tek
[[mailto:signrms@prog.cf][signrms@prog.cf]] ose
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

Nëse përsëri ju duhet ndihmë nga ana vizuale, shikoni
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][videon]].

*Firmat proçesohen maksimalisht brenda 12 orëve - për shkak të volumit
të Pull Requesteve* ## Chatrooms

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms

** Contact
   :PROPERTIES:
   :CUSTOM_ID: contact
   :END:

Nëse jeni gazetar, youtuber, ose përfaqësues të shtypit, mund të
kontaktoni tek ky email: - rms-support-letter@protonmail.com

** Licensing
   :PROPERTIES:
   :CUSTOM_ID: licensing
   :END:

Kodi në këtë repozitor kanë liçensën GPL-3.0-only

Imazhet tek folderi =assets= janë liçensuar sipas
[[https://creativecommons.org/licenses/by-sa/3.0/legalcode][CC BY-SA
3.0]]. Imazhet janë bazuar tek
https://commons.wikimedia.org/wiki/File:Richard_Matthew_Stallman.jpeg,
publikuar nën CC BY-SA 3.0, versioni i parë i së cilës ka qenë kopertinë
e librit të botuar nga O'Reilly
=Free as in Freedom: Richard Stallman's Crusade for Free Software by Sam Williams=,
publikuar më 21 Mars 2002 nën GFDL.
