* Une lettre ouverte en soutien à RMS
  :PROPERTIES:
  :CUSTOM_ID: une-lettre-ouverte-en-soutien-à-rms
  :END:

Pour la signer,
*[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][créez
un nouveau fichier]]* appelé =<nom>.yaml= (remplacez =<nom>= par votre
nom ou pseudo) avec le contenu suivant:

#+BEGIN_EXAMPLE
  name: <votre nom ici>
  link: <lien vers votre profil ou votre site>
#+END_EXAMPLE

Sans les =<>=.

Exemple:

#+BEGIN_EXAMPLE
  name: Jean Dupont
  link: https://example.com/
#+END_EXAMPLE

N'utilisez pas de =<>= dans le fichier, et utilisez uniquement des
caractères ASCII pour le nom du fichier. Si vous utilisez un email comme
lien, préfixez le avec =mailto:=. Utilisez de préférence votre vrai nom.
N'hésitez pas à ajouter les projets et/ou organisations auxquels vous
êtes affiliés entre parenthèses.

Lorsque vous avez terminé, *cliquez sur "Propose new file"* (Proposer un
nouveau fichier) et poursuivez la procédure afin de créer une demande de
fusion (Merge request).

Gardons le ton ferme, mais professionnel.

Pensez à partager cette lettre ouverte sur les forums et réseaux
sociaux, et à informer les journalistes qui pourraient être utiles à
notre cause.

Vous pouvez sinon effectuer une demande manuelle. Pour ce faire, créez
une fork de ce repo, ajoutez un fichier =_data/signed/<nom>.yaml= en
suivant les instructions ci-dessus, faites un commit puis une demande de
fusion.

Si vous voulez apporter votre soutien *sans utiliser GitHub*, allez ici:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, ou
envoyez un patch avec votre signature à
[[mailto:signrms@prog.cf][signrms@prog.cf]] ou
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

Si vous avez encore besoin d'aide avec des instructions visuelles,
utilisez [[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][cette
vidéo]].

*Les demandes sont traitées dans les 12 heures - en raison d'un énorme
volume de demandes de fusion.*

** Chatrooms (en Anglais)
   :PROPERTIES:
   :CUSTOM_ID: chatrooms-en-anglais
   :END:

- *Matrix.org:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
  ([[https://kiwiirc.com/client/irc.freenode.net/#free-rms][webchat]])
  (Jabber gateway : =#free-rms%chat.freenode.net@biboumi.marc-o.win= )
- *XMPP/jabber:*
  [[xmpp:support-rms@conf.marc-o.win?join][support-rms@conf.marc-o.win]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram*: https://t.me/free_rms

** Contact
   :PROPERTIES:
   :CUSTOM_ID: contact
   :END:

Si vous êtes un journaliste, un vidéaste ou un représentant d'un autre
organisme de presse, vous pouvez nous contacter avec cette addresse
email:

- [[mailto:rms-support-letter@protonmail.com][rms-support-letter@protonmail.com]]

** Licence
   :PROPERTIES:
   :CUSTOM_ID: licence
   :END:

Le code de ce dépôt est uniquement sous la licence GPL-3.0.

Les images du dossier =assets/= sont sous licence
[[https://creativecommons.org/licenses/by-sa/3.0/legalcode][CC BY-SA
3.0]]. Les images de l'aperçu sont basées sur
https://commons.wikimedia.org/wiki/File:Richard_Matthew_Stallman.jpeg,
publié sous la licence CC BY-SA 3.0, originellement publié comme
couverture du livre d'O'Reilly
=Free as in Freedom: Richard Stallman's Crusade for Free Software by Sam Williams=,
publié le 1er Mars 202 sous la licence GFDL.

Les signatures ne sont pas sujettes au copyright.
