* رسالة مفتوحة في دعم rms.
  :PROPERTIES:
  :CUSTOM_ID: رسالة-مفتوحة-في-دعم-rms.
  :END:

للتسجيل *اضغط
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][هنا]]*
وسمي الملف =<username>.yaml= (بدل =<username>= باسمك مع المحتوى التالي:)

#+BEGIN_EXAMPLE
  name: <your name here (optional organization or company)>
  link: <link to your profile or site>
#+END_EXAMPLE

بدون ال =<>=.

مثال:

#+BEGIN_EXAMPLE
  name: Example name (Good company)
  link: https://github.com/example_username
#+END_EXAMPLE

لا تستخدم =<>= في هذا الملف, اضافة الى رموز ليست ascii في اسم الملف. اذا
استخدمت ايميلك كرابط, اضف في بدياته =mailto:=. اذا تستطيع, الرجاء
استخدام اسمك الحقيقي واضافة مشاريع ومؤسسات في اقواس.

واضغط *click "Propose new file"* واذهب عبر الصحفات اللاحقة لتأليف merge
request.

لنبقي النبرة حازمة, لكن احترافية.

اذا تستطيع, الرجاء نشر هذا الرسالة على مواقع التواصل الاجتماع والمنتديات
وابلاغ الصحفيين الذين قد يكونوا مساعدين لقضيتنا.

*الpull requests تمزج في خلال 12 ساعة - بسبب وجود عدد كبير منهم سيتم
مزجهم في دفعات*

بدلا عن ذلك, فرع وانسخ المشروع, وانشاء ملف
=_data/signed/<username>.yaml= يدويا, وتسليم الpr.

اذا اردت دعم هذا الرسالة بدون استخدام غيت هاب, اذهب هنا:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, او
ارسل رقعة موقعة الى [[mailto:signrms@prog.cf][signrms@prog.cf]] او
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

** غرف دردشة
   :PROPERTIES:
   :CUSTOM_ID: غرف-دردشة
   :END:

- *Matrix.org:* #free-rms:matrix.org
- *IRC:* #free-rms at chat.freenode.net
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
