* Lettera aperta a favore di RMS
  :PROPERTIES:
  :CUSTOM_ID: lettera-aperta-a-favore-di-rms
  :END:

Per firmarla, crea un file nella cartella =_data/signed/= chiamato
=<username>.yaml= con:

#+BEGIN_EXAMPLE
  name: <il tuo nome>
  link: <link ad un tuo profilo o sito>
#+END_EXAMPLE

senza utilizzare =<>=.

Esempio:

#+BEGIN_EXAMPLE
  name: Nome Di Esempio
  link: https://example.com/
#+END_EXAMPLE

Non usare né =<>= in quel file né caratteri non ASCII nel nome del file.
Se puoi, usa il tuo nome reale e aggiungi i progetti e le organizzazioni
nelle quali fai parte tra parentesi.

Quando hai fatto, crea una pull request.

Se possibile, prendi in considerazione l'idea di condividere questa
lettera su forum, social media e di mandarla a giornalisti che
potrebbero essere utili alla nostra causa.

*Le pull request vengono approvate e unite nel giro di 12 ore - a causa
di un enorme numero di PR, saranno approvate e unite a gruppi*

** Contatti
   :PROPERTIES:
   :CUSTOM_ID: contatti
   :END:

- *Matrix.org:* #free-rms:matrix.org
- *IRC:* #free-rms at chat.freenode.net
- *Discord:* https://discord.gg/7FWkxG4CsU
