* Μια ανοιχτή επιστολή υπεράσπισης του RMS.
  :PROPERTIES:
  :CUSTOM_ID: μια-ανοιχτή-επιστολή-υπεράσπισης-του-rms.
  :END:

Για να υπογράψετε, *πατήστε
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][εδώ]]*
και ονομάστε το αρχείο =<username>.yaml= (αντικαταστήστε το =<username>=
με το δικό σας όνομα) και εισάγετε το παρακάτω περιεχόμενο:

#+BEGIN_EXAMPLE
  name: <το όνομα σας (αλλιώς το όνομα οργανισμού ή εταιρείας)>
  link: <link προς το προφίλ σας ή την ιστοσελίδα σας>
#+END_EXAMPLE

Αφαιρέστε τα σύμβλα =<>=.

Παράδειγμα:

#+BEGIN_EXAMPLE
  name: όνομα (εταιρεία)
  link: https://github.com/example_username
#+END_EXAMPLE

Μην χρησιμοποιείτε τα σύμβολα =<>= στο yaml αρχείο, ούτε μη-ASCII
σύμβολα στο όνομα του αρχείο. Αν χρησιμοποιήσετε το email σας ως link,
προσθέστε στην αρχή το =mailto:=. Εάν είναι εφικτό, παρακαλούμε να
χρησιμοποιήσετε το πραγματικό σας όνομα, και προσθέστε προσωπικά project
ή σχετικούς οργανισμούς εντός παρενθέσεων.

Έπειτα *πατήστε στο "Propose new file"* και ολοκληρώστε την διαδικασία
ώστε να πραγματοποιήσετε ένα merge request.

Διατηρήστε τον τόνο σας σκληρό, αλλά επαγγελματικό.

Εάν είναι εφικτό, παρακαλούμε διαδώστε το παρόν μήνυμα σε forums και
social media, και ειδοποιείστε δημοσιογράφους που είναι σε θέση να
υποστηρίξουν το σκοπό μας.

Ειδάλλως, μπορείτε να κλωνοποιήσετε το repo, να δημιουργήσετε νέο αρχείο
=_data/signed/<όνομα>.yaml=yaml=yaml= χειροκίνητα, έπειτα να εκτελέσετε
ένα commit και να υποβάλετε ένα PR.

Σε περίπτωση που θέλετε να υποστηρίξετε την ανοιχτή επιστολή χωρίς τη
χρήση Github, επισκεφθείτε την ιστοσελίδα:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, ή
στείλτε την ψηφιακή σας υπογραφή στο
[[mailto:signrms@prog.cf][signrms@prog.cf]] ή στο
[[mailto:~tyiltyiltyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

Εάν χρειάζεστε περαιτέρω βοήθεια μέσω βίντεο, παρακολουθήστε
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][αυτό]].

*Θα επεξεργαστούμε κάθε υπογραφή εντός 12 ωρών, λόγω μεγάλου αριθμού
υπογραφών*

** Chatrooms
   :PROPERTIES:
   :CUSTOM_ID: chatrooms
   :END:

- *Matrix:*
  [[https://matrix.to/#/#free-rms:matrix.org][#free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
