* Egy RMS-t támogató nyílt levél
  :PROPERTIES:
  :CUSTOM_ID: egy-rms-t-támogató-nyílt-levél
  :END:

Az aláíráshoz kattints
*[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][ide]]*,
add a fájlnak a =<username>.yaml= nevet (ahol =<username>= a te neved)
és legyen ez a tartalma:

#+BEGIN_EXAMPLE
  name: <A te neved (nem kötelezően szervezet vagy cég neve)>
  link: <Hivatkozás a profilodra vagy weboldaladra>
#+END_EXAMPLE

Kacsacsőrök nélkül.

Példa:

#+BEGIN_EXAMPLE
  name: Példa Név (Jó cég)
  link: https://github.com/pelda_nev
#+END_EXAMPLE

A fájl nevében ne használj kacsacsőröket, illetve karaktereket az ASCII
tartományon kívülről. Ha egy e-mail címet használsz a =link= mezőben,
akkor az elejét told meg =mailto:=-val. Ha lehetőséged adódik rá, legyél
szíves az igazi nevedet használni, zárójelek közé pedig projekteket,
szervezeteket és cégeket felsoroloni.

Majd *kattints a "Propose new file" gombra*, és az azt követő oldalakon
végigmenve hozz létre egy merge request-et.

Igyekezzünk a hangvételt erőteljesnek, de hivatásosnak megőrizni.

Ha van rá mód, legyél szíves megosztani ezt a levelet általad használt
fórumokon és közösségi médián, valamint újságíróknak felhívni a
figyelmét, akik hasznosan tudnak cselekedni az ügy érdekében.

Alternatívaként, készíts egy fork-ot, hozzad ott létre a
=_data/signed/<username>.yaml= fájlt manuálisan, majd abból készíts egy
Pull Request-et.

Ha *GitHub használata nélkül* szeretnéd támogatni a levelet, keresd fel
ezt a weboldalt:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1\\
vagy küldj egy aláírt patch-et a következő e-mail címekre:
[[mailto:signrms@prog.cf][signrms@prog.cf]],
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]]

Ha ezek után is szükséged van segítségre,
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][ez a videó]] a
hasznodra lehet.

*Minden aláírás feldolgozásra kerül maximum 12 órán belül a Pull
Request-ek nagy száma miatt*

** Chat szobák
   :PROPERTIES:
   :CUSTOM_ID: chat-szobák
   :END:

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms

** Licenc
   :PROPERTIES:
   :CUSTOM_ID: licenc
   :END:

A repository-ban lévő kód GPL-3.0-only licenc alatt áll.

A képek az =assets= mappában a
[[https://creativecommons.org/licenses/by-sa/3.0/legalcode][CC BY-SA
3.0]] licenc alatt állnak. A közösségi előnézeti kép alapjául szolgált a
CC BY-SA 3.0 licenc alatt publikált
https://commons.wikimedia.org/wiki/File:Richard_Matthew_Stallman.jpeg,
amely eredetileg a GFDL licenc alatt, O'Reilly által, 2002. március 2-án
kiadott,
=Free as in Freedom: Richard Stallman's Crusade for Free Software by Sam Williams=
című könyv borítóképeként szolgált.

Az aláírások nem állnak szerzői jogi védelem alatt.
