* نامه‌ای سرگشاده در حمایت از ریچارد استالمن
  :PROPERTIES:
  :CUSTOM_ID: نامهای-سرگشاده-در-حمایت-از-ریچارد-استالمن
  :END:

برای امضاکردن،
*[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][اینجا]]
کلیک کنید* و اسم فایل را =<username.yaml= (به جای =<username>= اسم
خودتان) به همراه محتوای ذیل:

#+BEGIN_EXAMPLE
  name: <اسم شما (شرکت یا ارگان شما به صورت اختیاری)>
  link: <لینک به پروفایل و یا وبسایت شما>
#+END_EXAMPLE

بدون =<>=.

مثال:

#+BEGIN_EXAMPLE
  name: Example name (Good company)
  link: https://github.com/example_username
#+END_EXAMPLE

از =<>= در این فایل استفاده نکنید، همچنین از نمادهای non-ascii در اسم
فایل استفاده نکنید. اگر از ایمیل‌تان به عنوان لینک استفاده می‌کنید،
مطمئن شوید با =mailto:= شروع شود. اگر برایتان مقدور است، لطفاً از اسم
واقعی خودتان و شرکت‌تان در پرانتز استفاده کنید.

سپس، *«Propose new file» را کلیک کنید* و به صفحات بعدی بروید تا یک
مرج‌ریکوئست ایجاد کنید.

بگذارید لحن را استوار، اما حرفه‌ای نگه داریم.

اگر برایتان مقدور است، اشتراک‌گذاری این نامه را در انجمن‌ها و شبکه‌های
اجتماعی و اطلاع‌رسانی به خبرنگارانی که ممکن است کمک کنند را در نظر
بگیرید.

متناوباً، این مخزن را فورک و کلون کنید، فایل
=_data/signed/<username>.yaml= را به صورت دستی بسازید، سپس کامیت کنید و
یک پول‌ریکوئست ثبت کنید.

اگر می‌خواهید نامه را پشتیبانی کنید بدون استفاده از گیت‌هاب، به اینجا
بروید:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1، یا
یک path امضاشده به [[mailto:signrms@prog.cf][signrms@prog.cf]] یا
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]]
بفرستید.

اگر همچنان به کمک از طریق دستورالعمل‌های بصری نیاز داشتید، از
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][این]] ویدیو استفاده
کنید.

*همهٔ امضاها حداکثر در ۱۲ ساعت مراحل را طی می‌کنند - با توجه به مقدار
زیاد پول‌ریکوئست‌ها*

** چت‌روم‌ها
   :PROPERTIES:
   :CUSTOM_ID: چترومها
   :END:

- *Matrix:*
  [[https://matrix.to/#/#free-rms:matrix.org][#free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
