* Carta aberta en apoio a RMS.
  :PROPERTIES:
  :CUSTOM_ID: carta-aberta-en-apoio-a-rms.
  :END:

Para asinala, *Faga click
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][aquí]]*
e coloque como nome do arquivo =<usuario>.yaml= (substitúa =<usuario>=
co seu nome) co seguinte contido:

#+BEGIN_EXAMPLE
  name: <Coloque aquí o seu nome (organización ou empresa, opcional)>
  link: <Enlace ao seu perfil ou páxina web>
#+END_EXAMPLE

Non coloque as chaves =<>=.

Exemplo:

#+BEGIN_EXAMPLE
  name: Nome de exemplo (Compañía serpa)
  link: https://github.com/usuario_de_exemplo
#+END_EXAMPLE

Non empregue =<>= neste arquivo, nin tampouco utilice caracteres
non-ascii no nome do arquivo (non colocar acentos, etc.). Si vostede
planea usar a súa dirección de correo electrónico como enlace, coloque
antes o prefixo =mailto:=. Si é posible, por favor use o seu nome real e
engada proxectos e organizacións afiliadas entre paréntese.

Logo, faga *click en "Propose new file"* e continúe nas páxinas
subsecuentes para crear unha petición de unir o arquivo.

Manteñamos o ton firme, pero profesional.

De ser posible, por favor considere compartir esta carta nos seus foros
e redes sociais, e avise a xornalistas que poidan ser útiles á nosa
causa.

*Peticións serán fusionadas cada 12 horas - debido ao gran volume de
peticións, serán fusionadas en lotes*

Outra forma de facelo é facendo 'fork' e clonando o repositorio, crear o
arquivo =_data/signed/<username>.yaml= manualmente, entón facer 'commit'
e enviar unha petición de 'pull'.

Si vostede quere apoiar esta carta sen usar Github, vaia aquí:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, ou
envíe un parche asinado a [[mailto:signrms@prog.cf][signrms@prog.cf]] ou
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

** Salas de chat
   :PROPERTIES:
   :CUSTOM_ID: salas-de-chat
   :END:

- *Matrix.org:* #free-rms:matrix.org
- *IRC:* #free-rms at chat.freenode.net
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
