* 'n Ope brief ter ondersteuning van RMS.
  :PROPERTIES:
  :CUSTOM_ID: n-ope-brief-ter-ondersteuning-van-rms.
  :END:

Om te onderteken, *klik
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][hier]]*
en benoem die leêr =<gebruikersnaam>.yaml= (vervang =<gebruikersnaam>=
met jou gebruikersnaam). Laat die leêr die volgende bevat:

#+BEGIN_EXAMPLE
  name: <jou naam hier (opsioneel jou organisasie)>
  link: <skakel na jou profiel of webtuiste>
#+END_EXAMPLE

Sonder die =<>=.

Byvoorbeeld:

#+BEGIN_EXAMPLE
  name: Example name (Good company)
  link: https://github.com/example_username
#+END_EXAMPLE

Moet nie =<>= of enige nie-ascii simbole in die leêr gebruik nie (dit
beteken geen leestkens soos kappies, akkutte of gravisse nie). As jy jou
epos-adres as skakel wil gebruik, maak seker jy sit die teks =mailto:=
voor jou adres. As jy kan, gebruik asseblief jou regte naam en sit die
organisasie waarmee jy geaffilieerd is in hakkies daarby.

Klik dan op *Propose new file* en gaan dan deur die daaropvolgende
blaaie om 'n merge request te maak.

Alternatiewelik, vurk en kloon hierdie repository, maak die leêr
=_data/signed/<gebruikersnaam>.yaml= jouself, en commit en maak dan 'n
pull request.

As jy die ope brief *sonder Github* wil ondersteun, gaan hier:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, of
stuur 'n signed patch aan [[mailto:signrms@prog.cf][signrms@prog.cf]] of
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

As jy visuele hulp benodig, kyk
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][hierdie]] video.

Laat ons die toon verm en professioneel hou.

As jy kan, oorweeg dit om díe brief in jou forums en sosiale media te
versprei. Laat weet ook asseblief joernaliste wie jy dink behulpsaam aan
ons saak kan wees.

*Alle handtekeninge sal binne 12 ure verwerk word. Dit as gevolg van hoë
volumes pull requests.*

** Kletskamers
   :PROPERTIES:
   :CUSTOM_ID: kletskamers
   :END:

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms on [[https://freenode.net][freenode]]
  ([[https://kiwiirc.com/client/irc.freenode.net/#free-rms][webchat]])
  (Jabber gateway : =#free-rms%chat.freenode.net@biboumi.marc-o.win= )
- *XMPP/jabber:*
  [[xmpp:support-rms@conf.marc-o.win?join][support-rms@conf.marc-o.win]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms

** Kontak
   :PROPERTIES:
   :CUSTOM_ID: kontak
   :END:

As jy 'n lid van die pers is kan jy ons by die onderstaande epos-adres
kontak: - rms-support-letter@protonmail.com
