* Een open brief ter ondersteuning van RMS.
  :PROPERTIES:
  :CUSTOM_ID: een-open-brief-ter-ondersteuning-van-rms.
  :END:

Om te ondertekenen, *klik
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][hier]]*
en noem het bestand =<gebruikersnaam>.yaml= (vervang =<gebruikersnaam>=
met uw naam) met de volgende inhoud:

#+BEGIN_EXAMPLE
  name: <uw naam hier (optionele organisatie of bedrijf)>
  link: <link naar uw profiel of site>
#+END_EXAMPLE

Zonder de =<>=.

Voorbeeld:

#+BEGIN_EXAMPLE
  name: Voorbeeld Naam (Goed bedrijf)
  link: https://github.com/voorbeeld_gebruikersnaam
#+END_EXAMPLE

Gebruik geen =<>= in dit bestand, evenals niet-ascii tekens in het
bestandsnaam. Als u uw e-mailadres gebruikt als link, plaatst u daarvoor
=mailto:=. Als het kan, gebruik alstublieft uw echte naam en voeg
projecten en aangesloten organisaties toe in haakjes.

Dan *klik op "Propose new file"* en doorloop de volgende pagina's om een
merge request aan te maken.

Laten we de toon stevig maar professioneel houden.

Als het kan, overweeg dan om deze brief op forums en sociale media te
delen en journalisten op de hoogte te brengen die onze zaak kunnen
helpen.

U kunt ook de repo splitsen en klonen, het bestand
=_data/signed/<gebruikersnaam>.yaml= handmatig aanmaken, vervolgens
committen en een PR indienen.

Als je de brief wilt ondersteunen zonder Github te gebruiken, ga dan
hier naartoe:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, of
stuur een ondertekende patch naar
[[mailto:signrms@prog.cf][signrms@prog.cf]] of
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

Als u nog steeds hulp nodig heeft via visuele instructies, gebruik
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][deze]] video.

*Alle handtekeningen worden binnen maximaal 12 uur verwerkt - vanwege
een enorm aantal PR's*

** Chatrooms
   :PROPERTIES:
   :CUSTOM_ID: chatrooms
   :END:

- *Matrix.org:* #free-rms:matrix.org
- *IRC:* #free-rms at chat.freenode.net
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
