* Ein offener Brief zur Unterstützung von RMS.
  :PROPERTIES:
  :CUSTOM_ID: ein-offener-brief-zur-unterstützung-von-rms.
  :END:

Um zu unterschreiben, *clicke
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][hier]]*
und nenne die Datei =<Nutzername>.yaml= (Ersetzte =<Nutzername>= mit
deinem Namen) mit folgendem Inhalt:

#+BEGIN_EXAMPLE
  name: <Dein Name hier (optional Organisation oder Firma)>
  link: <Link zu deinem Profil oder deiner Website>
#+END_EXAMPLE

Ohne das=<>=.

z.B.:

#+BEGIN_EXAMPLE
  name: Beispiel Name (Gute Firma)
  link: https://github.com/Beispiel_nutzername
#+END_EXAMPLE

Benutze in dieser Datei =<>= nicht, und verwende im Dateinamen keine
nicht-ascii Symbole . Wenn du deine E-Mail als Link verwendest, stelle
sie mit =mailto=: voran. Wenn es dir möglich ist, nutze bitte deinen
echten Namen und füge Projekte und verbundene Organisationen in Klammern
hinzu.

Clicke dann *"Propose new file"* (Neue Datei vorschlagen) und gehe die
folgenden Seiten durch, um ein Merge-Request zu erstellen.

Lass uns den Ton fest, aber professionell halten.

Wenn du kannst, teile diesen Brief bitte in deinen Foren und sozialen
Medien und benachrichtige Journalisten, die eventuell hilfreich für
unsere Sache sein könnten.

Alternativ kannst du auch das Repo forken und clonen und die Datei
=_data/signed/<Nutzername>.yaml= manuell erstellen, dann commiten und
ein Pull Request einreichen.

Wenn du nicht GitHub verwenden möchtest, kannst du auch: - Ein
unterschriebenes Patch an [[mailto:signrms@prog.cf][signrms@prog.cf]]
schicken. - Oder an
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]]. -
Oder unterschreibe hier:
[[https://codeberg.org/rms-support-letter/rms-support-letter/issues/1]]

Falls du visuelle Hilfe benötigst, verwende
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][dieses]] Video
(Englisch).

*Alle Unterschriften werden - aufgrund der enormen Menge an
Pull-Requests - innerhalb von maximal 12 Stunden verarbeitet.*

** Chaträume (Englisch)
   :PROPERTIES:
   :CUSTOM_ID: chaträume-englisch
   :END:

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms auf [[https://freenode.net][freenode]]
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms
