* Isang bukas na liham para suportahan si RMS.
  :PROPERTIES:
  :CUSTOM_ID: isang-bukas-na-liham-para-suportahan-si-rms.
  :END:

Para pumirma, *i-click
[[https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed][ito]]*
at pangalanan ang file na =<username>.yaml= (palitan ang =<username>= sa
iyong pangalan) na naglalaman ng:

#+BEGIN_EXAMPLE
  name: <pangalan mo (opsyonal na organisasyon o kumpanya)>
  link: <kawing sa iyong profile o pook>
#+END_EXAMPLE

Hindi kasama ang =<>=.

Halimbawa:

#+BEGIN_EXAMPLE
  name: Halimbawang pangalan (Mabuting kumpanya)
  link: https://github.com/halimbawang_username
#+END_EXAMPLE

Huwag gamitin ang =<>= sa file na ito, pati na rin ang mga simbolong
hindi kasama sa ascii para sa pangalan ng file. Kung ginagamit mo ang
iyong e-liham bilang kawing, lagyan mo ng =mailto:= sa simula. Kung
puwede, gamitin mo ang tunay mong pangalan at ilagay mo ang mga proyekto
at naka-anib na organisasyon sa saklong.

Tapos *i-click ang "Propose new file"* at sundin ang kailangang gawin
para gumawa ng merge request.

Panatilihin nating matatag ang tono, pero propesyunal.

Kung kaya mo, i-kunsidera mo ang pamamahagi ng liham na ito sa iyong mga
forum at social media, at ipabatid sa mga manunulat na makakatulong sa
ating pinaglalaban.

Puwede rin i-fork at clone ang repo. Gumawa ng file na
=_data/signed/<username>.yaml= nang manu-mano, tapos i-commit at
mag-submit ng PR.

Kung gusto mong suportahan ang liham nang *hindi ginagamit ang Github*,
puntahan ito:
https://codeberg.org/rms-support-letter/rms-support-letter/issues/1, o
magpadala ng nakapirmang tapal sa
[[mailto:signrms@prog.cf][signrms@prog.cf]] o
[[mailto:~tyil/rms-support@lists.sr.ht][~tyil/rms-support@lists.sr.ht]].

Kung kailangan mo pa rin ng tulong sa pamamagitan ng biswal na
tagubilin, may
[[https://invidious.snopyta.org/watch?v=1lz5S5oS8CU][bidyo]] para rito.

*** Nagbago ba ang isip mo at gusto mong ipatanggal ang iyong pirma mula
sa liham laban kay Richard Stallman?
    :PROPERTIES:
    :CUSTOM_ID: nagbago-ba-ang-isip-mo-at-gusto-mong-ipatanggal-ang-iyong-pirma-mula-sa-liham-laban-kay-richard-stallman
    :END:

Puwede mong ipakita ang iyong intensyon dito:
https://github.com/rms-support-letter/revoke-open-letter-signature

** Mga silid pang-usap
   :PROPERTIES:
   :CUSTOM_ID: mga-silid-pang-usap
   :END:

- *Matrix:*
  [[https://matrix.to/#/+free-rms:matrix.org][+free-rms:matrix.org]]
- *IRC:* #free-rms sa [[https://freenode.net][freenode]]
- *XMPP/jabber:* support-rms@conf.marc-o.win
- *Discord:* https://discord.gg/7FWkxG4CsU
- *Telegram:* https://t.me/free_rms

** Kaibigan namin
   :PROPERTIES:
   :CUSTOM_ID: kaibigan-namin
   :END:

https://stallmansupport.org/

** Makipag-ugnay
   :PROPERTIES:
   :CUSTOM_ID: makipag-ugnay
   :END:

Kung isa kang miyembro o kumakatawan ng isang pahayagan, o isang
youtuber, puwede kang makipag-ugnay sa amin sa pamamagitan ng e-liham: -
[[mailto:rms-support-letter@protonmail.com][rms-support-letter@protonmail.com]]

** Lisensiya
   :PROPERTIES:
   :CUSTOM_ID: lisensiya
   :END:

Ang kodigo sa imbakan na ito ay nakalisensya lamang sa GPL-3.0.

Ang mga larawan sa =assets= folder ay nakalisensiya sa ilalim ng CC
BY-SA 3.0. Ang mga larawang preview para sa social media ay nakabatay sa
https://commons.wikimedia.org/wiki/File:Richard_Matthew_Stallman.jpeg,
na nasa ilalim ng CC BY-SA 3.0. Orihinal itong inilathala bilang pabalat
larawan ng libro ni O'Reilly na
=Free as in Freedom: Richard Stallman's Crusade for Free Software by Sam Williams=,
noong Marso 1, 2002 sa ilalim ng GFDL.

Walang kopirayt ang mga pirma.
